### ISSUE TITLE
Each page missing a live link of your Year Up email address 

### ISSUE THREAD

**Issue by justinfujimoto** [hayzull/hazelweb#1]
Severity:
3. Minor Problem

Priority:
2. Must fix before product release

Environment: Mozilla 43.0.4

Description:
Missing your Year Up email address on ALL pages

**Comment by hayzull** [comment]
![email](https://cloud.githubusercontent.com/assets/16563456/12303724/bcaf2894-b9e0-11e5-94e4-818660c81c0c.PNG)

added an email me link
